version: '3.8'

services:
  auctionservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080"
      - "8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro

  postgres:
    container_name: postgres.db
    environment:
      - POSTGRESQL_USERNAME=tanlan
      - POSTGRESQL_PASSWORD=admin1234
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - local

  mongodb:
    container_name: mongodb
    environment:
      - MONGODB_USERNAME=root
      - MONGODB_PASSWORD=mongopw
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/var/lib/mongodb/data
    networks:
      - local
