version: '3.8'

services:
  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile


  postgres:
    image: bitnami/postgresql:latest

networks:
  local:
    driver: bridge
volumes:
  postgres_data:
