version: '3.9'

services:
  auctionservice:
    image: ${DOCKER_REGISTRY-}auctionservice
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile


  postgres:
    image: postgresql:latest

  mongodb:
    image: mongodb:latest

networks:
  local:
    driver: bridge
volumes:
  postgres_data:
  mongo_data:
