import './globals.css';
import Navbar from './nav/Navbar';
import { ReactNode } from 'react';

export const metadata = {
	title: 'Carsties',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: ReactNode;
}) {
	return (
		<html lang='en'>
			<body>
				<Navbar />
				<main className='container mx-auto px-5 pt-10'>{children}</main>
			</body>
		</html>
	);
}
